import React from 'react';

import './main.scss';

export const Main = () => (
  <main className="main">
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus iste repudiandae ea suscipit, voluptates facilis maiores a molestiae sit eveniet pariatur distinctio sed corrupti recusandae tempora, saepe debitis! Nostrum, velit mollitia architecto ab hic voluptatem aliquam quibusdam eligendi! Magnam, quas inventore! Iste alias ea excepturi accusamus laborum consequuntur eos. Voluptates officiis numquam voluptatibus sequi quibusdam consequatur fugiat sint, assumenda aut consectetur sapiente laboriosam autem quod unde! Autem natus quod commodi eligendi et quo in esse reiciendis vero ea atque beatae, quos ab incidunt? Rerum inventore quidem sequi debitis, a repudiandae qui perferendis. Expedita nisi delectus architecto cupiditate consequatur praesentium ab.</p>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus iste repudiandae ea suscipit, voluptates facilis maiores a molestiae sit eveniet pariatur distinctio sed corrupti recusandae tempora, saepe debitis! Nostrum, velit mollitia architecto ab hic voluptatem aliquam quibusdam eligendi! Magnam, quas inventore! Iste alias ea excepturi accusamus laborum consequuntur eos. Voluptates officiis numquam voluptatibus sequi quibusdam consequatur fugiat sint, assumenda aut consectetur sapiente laboriosam autem quod unde! Autem natus quod commodi eligendi et quo in esse reiciendis vero ea atque beatae, quos ab incidunt? Rerum inventore quidem sequi debitis, a repudiandae qui perferendis. Expedita nisi delectus architecto cupiditate consequatur praesentium ab.</p>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus iste repudiandae ea suscipit, voluptates facilis maiores a molestiae sit eveniet pariatur distinctio sed corrupti recusandae tempora, saepe debitis! Nostrum, velit mollitia architecto ab hic voluptatem aliquam quibusdam eligendi! Magnam, quas inventore! Iste alias ea excepturi accusamus laborum consequuntur eos. Voluptates officiis numquam voluptatibus sequi quibusdam consequatur fugiat sint, assumenda aut consectetur sapiente laboriosam autem quod unde! Autem natus quod commodi eligendi et quo in esse reiciendis vero ea atque beatae, quos ab incidunt? Rerum inventore quidem sequi debitis, a repudiandae qui perferendis. Expedita nisi delectus architecto cupiditate consequatur praesentium ab.</p>
    <a href="#" title="Шутка, продолжения нет))">To be continue...</a>
  </main>
);
